import Sidebar from "@/components/partials/Sidebar";
import "@/styles/globals.css";
import Providers from "@/utils/Providers";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <div className="react-root">
            <div className="min-h-[100dvh] pointer-events-auto z-0 flex flex-row w-full">
              <Sidebar />
              <main className="flex flex-col items-start shrink grow">
                <div className="flex flex-col w-[1050px] shrink grow">
                  <div
                    className="grow flex flex-col"
                    style={{
                      backfaceVisibility: "hidden",
                    }}
                  >
                    <div className="min-h-full justify-between items-stretch bg-transparent flex flex-row grow w-full">
                      <div className="z-[1] bg-black max-w-[600px] grow w-full mx-0 border-r-[1px] border-l-[1px] border-[#2f3336]">
                        {children}
                      </div>
                    </div>
                  </div>
                </div>
              </main>
            </div>
          </div>
        </Providers>
      </body>
    </html>
  );
}
