import Footer from "@/components/partials/Footer";
import Sidebar from "@/components/partials/Sidebar";
import "@/styles/globals.css";
import Providers from "@/utils/Providers";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <main>
            <Sidebar />
            <div className="app">{children}</div>
            <Footer />
          </main>
        </Providers>
      </body>
    </html>
  );
}
